# use v2.x API to allow `mem_limit` option
version: "2.4"
services:
  persistence:
    image: janssenproject/persistence-loader:1.0.0_dev
    environment:
      - CN_CONFIG_CONSUL_HOST=consul
      - CN_SECRET_VAULT_HOST=vault
      - CN_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - CN_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - CN_LDAP_URL=ldap:1636
      - CN_COUCHBASE_URL=${COUCHBASE_URL}
      - CN_COUCHBASE_USER=${COUCHBASE_USER}
      - CN_COUCHBASE_SUPERUSER=${COUCHBASE_SUPERUSER}
      - CN_OXTRUST_API_ENABLED=${OXTRUST_API_ENABLED}
      - CN_OXTRUST_API_TEST_MODE=${OXTRUST_API_TEST_MODE}
      - CN_PASSPORT_ENABLED=${PASSPORT_ENABLED}
      - CN_CASA_ENABLED=${CASA_ENABLED}
      - CN_RADIUS_ENABLED=${RADIUS_ENABLED}
      - CN_SAML_ENABLED=${SAML_ENABLED}
      - CN_SCIM_ENABLED=${SCIM_ENABLED}
      - CN_SCIM_TEST_MODE=${SCIM_TEST_MODE}
      - CN_PERSISTENCE_SKIP_EXISTING=${PERSISTENCE_SKIP_EXISTING}
      - CN_CACHE_TYPE=${CACHE_TYPE}
      - CN_REDIS_URL=${REDIS_URL}
      - CN_REDIS_TYPE=${REDIS_TYPE}
      - CN_REDIS_USE_SSL=${REDIS_USE_SSL}
      - CN_REDIS_SSL_TRUSTSTORE=${REDIS_SSL_TRUSTSTORE}
      - CN_REDIS_SENTINEL_GROUP=${REDIS_SENTINEL_GROUP}
      - CN_DOCUMENT_STORE_TYPE=${DOCUMENT_STORE_TYPE}
      - CN_JACKRABBIT_URL=http://jackrabbit:8080
      - CN_JACKRABBIT_ADMIN_ID=${JACKRABBIT_USER}
      - CN_JACKRABBIT_ADMIN_PASSWORD_FILE=/etc/jans/conf/jackrabbit_admin_password
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: persistence
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/jans/conf/couchbase_password
      - ./couchbase_superuser_password:/etc/jans/conf/couchbase_superuser_password
      - ./jackrabbit_admin_password:/etc/jans/conf/jackrabbit_admin_password
    restart: on-failure
    mem_limit: 512M
