# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  client-api:
    image: janssenproject/client-api:5.0.0_dev
    environment:
      - CN_CONFIG_CONSUL_HOST=consul
      - CN_SECRET_VAULT_HOST=vault
      - CN_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - CN_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - CN_LDAP_URL=ldap:1636
      - CN_COUCHBASE_URL=${COUCHBASE_URL}
      - CN_COUCHBASE_USER=${COUCHBASE_USER}
      - CN_OXD_APPLICATION_CERT_CN=client-api
      - CN_OXD_ADMIN_CERT_CN=client-api
    container_name: client-api
    restart: unless-stopped
    mem_limit: 1024M
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/gluu/conf/couchbase_password
