# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  config-api:
    image: janssenproject/config-api:1.0.0_dev
    environment:
      - CN_CONFIG_CONSUL_HOST=consul
      - CN_SECRET_VAULT_HOST=vault
      - CN_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - CN_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - CN_LDAP_URL=ldap:1636
      - CN_COUCHBASE_URL=${COUCHBASE_URL}
      - CN_COUCHBASE_USER=${COUCHBASE_USER}
      - CN_SSL_CERT_FROM_SECRETS=true
    container_name: config-api
    restart: unless-stopped
    mem_limit: 1024M
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/jans/conf/couchbase_password
    labels:
      - "SERVICE_NAME=jans-config-api"
      - "SERVICE_8074_CHECK_HTTP=/health-check"
      - "SERVICE_8074_CHECK_INTERVAL=30s"
      - "SERVICE_8074_CHECK_TIMEOUT=30s"
