# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  oxshibboleth:
    image: gluufederation/oxshibboleth:5.0.0_dev
    environment:
      - CN_CONFIG_CONSUL_HOST=consul
      - CN_SECRET_VAULT_HOST=vault
      - CN_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - CN_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - CN_LDAP_URL=ldap:1636
      - CN_COUCHBASE_URL=${COUCHBASE_URL}
      - CN_COUCHBASE_USER=${COUCHBASE_USER}
      - CN_DOCUMENT_STORE_TYPE=${DOCUMENT_STORE_TYPE}
      - CN_JACKRABBIT_URL=http://jackrabbit:8080
      - CN_JACKRABBIT_ADMIN_ID=${JACKRABBIT_USER}
      - CN_JACKRABBIT_ADMIN_PASSWORD_FILE=/etc/gluu/conf/jackrabbit_admin_password
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxshibboleth
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/gluu/conf/couchbase_password
      - ./jackrabbit_admin_password:/etc/gluu/conf/jackrabbit_admin_password
    mem_limit: 1024M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxshibboleth"
      - "SERVICE_8086_CHECK_HTTP=/idp"
      - "SERVICE_8086_CHECK_INTERVAL=30s"
      - "SERVICE_8086_CHECK_TIMEOUT=30s"
      - "APP_NAME=oxshibboleth"
