# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  auth-server:
    image: janssenproject/auth-server:1.0.0_dev
    environment:
      - CN_CONFIG_CONSUL_HOST=consul
      - CN_SECRET_VAULT_HOST=vault
      - CN_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - CN_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - CN_LDAP_URL=ldap:1636
      - CN_COUCHBASE_URL=${COUCHBASE_URL}
      - CN_COUCHBASE_USER=${COUCHBASE_USER}
      - CN_DOCUMENT_STORE_TYPE=${DOCUMENT_STORE_TYPE}
      - CN_JACKRABBIT_URL=http://jackrabbit:8080
      - CN_JACKRABBIT_ADMIN_ID=${JACKRABBIT_USER}
      - CN_JACKRABBIT_ADMIN_PASSWORD_FILE=/etc/jans/conf/jackrabbit_admin_password
      - CN_SSL_CERT_FROM_SECRETS=true
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: auth-server
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/jans/conf/couchbase_password
      - ./jackrabbit_admin_password:/etc/jans/conf/jackrabbit_admin_password
      - /home/iromli/work/janssen/jans-pycloudlib:/src/jans-pycloudlib
      - /home/iromli/work/janssen/docker-jans-auth-server/scripts:/app/scripts
    mem_limit: 1536M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=jans-auth"
      - "SERVICE_8080_CHECK_HTTP=/jans-auth/sys/health-check"
      - "SERVICE_8080_CHECK_INTERVAL=30s"
      - "SERVICE_8080_CHECK_TIMEOUT=30s"
      - "APP_NAME=jans-auth"
